### ISSUE TITLE
Missing data for EOMA68 Computing devices

### ISSUE THREAD

**Issue by damamitesh** [OPEN-NEXT/LOSH-list#15]
1. Not approved by bot, FSF and OSI (License - LAL 1.2
2. Github repo missing
3. No information regarding licensor
@moedn

**Comment by moedn** [comment]
1. LAL 1.2 was added to the whitelist (see https://github.com/OPEN-NEXT/LOSH-list/blob/main/license-whitelist)
2. jepp, couldn't find anything
3. jepp, no documentation, no licensor (although I believe that [Luke Kenneth Casson Leighton](https://www.crowdsupply.com/people/lkcl) alone is working on this; maybe there will be a release somewhere some day

**Comment by moedn** [comment]
other possible computers might be

- https://www.kosagi.com/w/index.php?title=Novena_Main_Page (shuttleworth-funded)
- https://beagleboard.org/
