### ISSUE TITLE
Couldn't find repo for Frachtstück project

### ISSUE THREAD

**Issue by damamitesh** [OPEN-NEXT/LOSH-list#19]
@moedn  any information or links?

**Comment by moedn** [comment]
1. they seem to use a dropbox: https://www.dropbox.com/sh/int6hpsbvspp111/AADPumKs_Pte9Y-qZoc3wGsea?dl=0&lst=
2. they use CC-BY-NC-4.0 → that's not compliant to OSHWA/OSI or FSF-terms → not an open source license (although they are using the term on their webpage)

we could eMail them and ask if they want to a) move to git and b) choose an open source license (as CC-BY-SA-4.0 or just CERN-OHL-S-2.0)

I'll delete the file for now until license compliance is resolved, but we can always go back when referring to this commit :)

https://github.com/OPEN-NEXT/LOSH-list/commit/76ecaacc44efef2375cccf0f74a7b9c0e8c80b2d
