### ISSUE TITLE
create license-whitelist.json in extra repo (+blacklist)

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH-list#22]
like this: https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json

into this repo: https://github.com/OPEN-NEXT/LOSH-Licenses

JSON includes:

- name
- URL to legal code
- SPDX ID

https://raw.githubusercontent.com/OPEN-NEXT/LOSH/master/Data%20Mapping/SPDX-blacklist

**Comment by moedn** [comment]
true! will change that now

**Comment by moedn** [comment]
dude, you're super fast! I created this issue minutes ago

**Comment by moedn** [comment]
plain text lists created here: https://github.com/OPEN-NEXT/LOSH-Licenses/

**Comment by penyuan** [comment]
> dude, you're super fast! I created this issue minutes ago

Haha I mean I'm pretty late in general to the issues in the LOSH-related repos...

**Comment by moedn** [comment]
done
