### ISSUE TITLE
Platform list platforms

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH-list#23]
- https://www.docubricks.com/
- Wikifab
- thingiverse
- github
- gitlab
- gitea
- maker.pro
- OSEG wiki
- OSE wiki
- (may be bullshit:) https://www.tinkercad.com/
- https://projects.humanitarianmaking.org/
- https://www.open-electronics.org/
- https://learn.adafruit.com/guides/projects
- https://www.latelierpaysan.org/Technical-drawings-tutorials

**Comment by moedn** [comment]
Please still add the following platforms to the analysis:

- [ ] Wikifactory
- [ ] Appropedia

**Comment by damamitesh** [comment]
Updated :)  Can you add the integration type for appropedia and wikifactory? @moedn 

Thanks
